### ISSUE TITLE
Falsche npm commands

### ISSUE THREAD

**Issue by LOFWagner** [DennisSchulmeister/dhbwka-wwi-vertsys-2024-quellcodes#7]
Bei [https://github.com/DennisSchulmeister/dhbwka-wwi-vertsys-2024-quellcodes/blob/main/1%20Architektur%20verteilter%20Systeme/Beispiele/Notebook-as-a-Service/README.md](url) gibt es einen Fehler mit den NPM commands. Das nutzen von verschiedenen Zusätzen wie start1, start2 und start:exercise muss man ein "run" ergänzen, damit es klappt.
Sprich statt "npm start:exercise" müsste es "npm run start:exercise" sein.

**Comment by DennisSchulmeister** [comment]
Danke für den Hinweis. Ich korrigiere es gleich.
